### ISSUE TITLE
GuidedUSCal

### ISSUE THREAD

**Issue by yogeren** [lgroves6/GuidedUltraSoundCalibration#1]
Hi~
I want to create the extension of the "GuidedUSCal", but I have met some problems. Do you have some tutorials about How to create the extension in the slicer and use the "GuidedUSCal"？
Thanks, all the best!

**Comment by yogeren** [comment]
Traceback (most recent call last):
  File "E:/Slicer 4.10.2/Extensions/GuidedUltraSoundCalibration/GuidedUSCal/GuidedUSCal.py", line 42, in __init__
    self.logic = GuidedUSCalLogic()
  File "E:/Slicer 4.10.2/Extensions/GuidedUltraSoundCalibration/GuidedUSCal/GuidedUSCal.py", line 421, in __init__
    self.regLogic = slicer.modules.guideduscalalgo.logic()
AttributeError: 'module' object has no attribute 'guideduscalalgo'

**Comment by lgroves6** [comment]
Hi there,

Please send me an email at lgroves6@uwo.ca and I will help you get everything you need to get this working. 

Thanks for the interest!

**Comment by yogeren** [comment]
Hi~ 

I have sent an email at lgroves6@uwo.ca  already, please help me with the problem~

Sorry to bother you. Thanks!!
